keywords:
  - TSLA
  - NVDA
  - Elon Musk
  - AI
  - Trump
  - nuclear power
  - SMR
  - nuclear policy
  - nuclear energy

low_quality_sources:
  - "Yahoo Entertainment"
  - "TMZ"
  - "Hollywood Reporter"
